[package]
name = "kariba-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
kariba-core.workspace = true
kariba-ipc.workspace = true
kariba-survey.workspace = true
libc.workspace = true
serde_json.workspace = true
